/**
 * Builds supabase/seed.sql from the catalog CSVs (the source of truth) using the same validator as
 * the admin importer. Run with `npm run catalog:seed`; `--check` fails if seed.sql is stale (CI).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildCatalogPayload, buildOfferRecords, csvRecords, dollarsToCents } from '@pickledeals/shared';

const here = dirname(fileURLToPath(import.meta.url));
const read = (name: string) => readFileSync(join(here, 'catalog', name), 'utf8');
const readDev = (name: string) => readFileSync(join(here, 'dev', name), 'utf8');

const { payload, issues } = buildCatalogPayload({
  brands: read('brands.csv'),
  categories: read('categories.csv'),
  products: read('products.csv'),
});

if (issues.length) {
  for (const i of issues) console.error(`${i.file}.csv:${i.line} ${i.message}`);
  process.exit(1);
}

const json = JSON.stringify(payload);
if (json.includes('$catalog$')) throw new Error('payload contains the SQL dollar-quote tag');

// --- Dev retail data (local only; fictional prices) ---------------------------------------------
const retailers = csvRecords(readDev('retailers.csv')).map(({ values }) => values);
const offers = buildOfferRecords(readDev('offers.csv'));
if (offers.issues.length) {
  for (const i of offers.issues) console.error(`dev/offers.csv:${i.line} ${i.message}`);
  process.exit(1);
}
const promos = csvRecords(readDev('promos.csv')).map(({ values: r }) => ({
  retailer_slug: r.retailer_slug,
  code: r.code,
  title: r.title,
  discount_type: r.discount_type,
  discount_value: Number(r.discount_value),
  min_purchase_cents: r.min_purchase_usd ? dollarsToCents(r.min_purchase_usd) : 0,
  target_kind: r.target_kind || null,
  target_slug: r.target_slug || null,
  ends_in_days: Number(r.ends_in_days),
  verified_days_ago: Number(r.verified_days_ago),
  is_exclusive: r.is_exclusive === 'yes',
}));
const retailJson = { retailers: JSON.stringify(retailers), offers: JSON.stringify(offers.records), promos: JSON.stringify(promos) };
for (const v of Object.values(retailJson)) if (v.includes('$dev$')) throw new Error('dev data contains the SQL dollar-quote tag');

const sql = `-- GENERATED by supabase/seed/build-seed.ts from supabase/seed/catalog/*.csv — do not edit.
-- Development catalog: real brands and models; MSRPs are approximate (see supabase/seed/README.md).
-- ${payload.brands.length} brands · ${payload.categories.length} categories · ${payload.products.length} products
do $seed$
declare
  report jsonb;
begin
  report := public.import_catalog($catalog$${json}$catalog$::jsonb, false);
  if not (report ->> 'applied')::boolean then
    raise exception 'catalog seed failed: %', report -> 'errors';
  end if;
  raise notice 'catalog seed: %', report - 'errors';
end;
$seed$;

-- DEVELOPMENT RETAIL DATA (supabase/seed/dev/*.csv): fictional prices for local testing only.
-- Fictional shops use reserved .example domains; Amazon offers carry no price (D1).
-- ${retailers.length} retailers · ${offers.records.length} offer rows · ${promos.length} promo codes
insert into public.retailers (slug, name, kind, domain, price_display_default)
select slug, name, kind::public.retailer_kind, domain, price_display_default::public.price_display
  from jsonb_to_recordset($dev$${retailJson.retailers}$dev$::jsonb)
       as x(slug text, name text, kind text, domain text, price_display_default text);

do $offers$
declare
  report jsonb;
begin
  report := public.ingest_offers('csv', $dev$${retailJson.offers}$dev$::jsonb, false);
  if not (report ->> 'applied')::boolean then
    raise exception 'dev offer seed failed: %', report -> 'errors';
  end if;
  raise notice 'dev offers: %', report - 'errors' - 'queued';
end;
$offers$;

-- Synthetic 120-day history for priced offers, so charts and deal quality have data: a gentle
-- random walk with retail-style prices ($x.99), changing every few days.
do $history$
declare
  o     record;
  d     integer;
  price integer;
begin
  perform setseed(0.42);
  for o in select id, price_cents, shipping_cents from public.retailer_offers where price_display = 'show' order by external_ref nulls first, url loop
    price := round(o.price_cents * (0.98 + random() * 0.14));
    for d in reverse 120..1 loop
      if d % 5 = 0 and random() < 0.6 then
        price := greatest(round(price * (0.955 + random() * 0.09) / 100) * 100 - 1, 99);
        insert into public.price_points (offer_id, observed_at, price_cents, shipping_cents, in_stock, price_display)
        values (o.id, now() - make_interval(days => d), price, o.shipping_cents, true, 'show');
      end if;
    end loop;
  end loop;
end;
$history$;

insert into public.promo_codes (retailer_id, code, title, discount_type, discount_value, min_purchase_cents, ends_at, verified_at, is_exclusive)
select r.id, p.code, p.title, p.discount_type::public.discount_type, p.discount_value, p.min_purchase_cents,
       now() + make_interval(days => p.ends_in_days), now() - make_interval(days => p.verified_days_ago), p.is_exclusive
  from jsonb_to_recordset($dev$${retailJson.promos}$dev$::jsonb)
       as p(retailer_slug text, code text, title text, discount_type text, discount_value int, min_purchase_cents int,
            target_kind text, target_slug text, ends_in_days int, verified_days_ago int, is_exclusive boolean)
  join public.retailers r on r.slug = p.retailer_slug;

insert into public.promo_code_targets (promo_id, product_id, category_id)
select pc.id,
       case when p.target_kind = 'product' then (select id from public.products where slug = p.target_slug) end,
       case when p.target_kind = 'category' then (select id from public.categories where slug = p.target_slug) end
  from jsonb_to_recordset($dev$${retailJson.promos}$dev$::jsonb) as p(retailer_slug text, code text, target_kind text, target_slug text)
  join public.retailers r on r.slug = p.retailer_slug
  join public.promo_codes pc on pc.retailer_id = r.id and pc.code = p.code
 where p.target_kind is not null;

select public.refresh_variant_price_stats(variant_id) from (select distinct variant_id from public.retailer_offers) v;

-- Dev curation: a staff pick, an editorial collection and a labelled sponsored placement.
update public.deals d set is_staff_pick = true
  from public.product_variants v join public.products p on p.id = v.product_id
 where d.variant_id = v.id and d.status = 'active' and p.slug = 'selkirk-vanguard-power-air-invikta';

insert into public.collections (slug, title, subtitle, eyebrow, sort)
values ('court-shoes-on-sale', 'Court shoes on sale', 'Pickleball-specific shoes at their best prices', 'STAFF PICKS · UPDATED DAILY', 1);
insert into public.collection_items (collection_id, product_id, sort)
select c.id, p.id, row_number() over (order by p.name)
  from public.collections c, public.products p join public.categories cat on cat.id = p.category_id
 where c.slug = 'court-shoes-on-sale' and cat.slug = 'shoes';

insert into public.placements (kind, deal_id, campaign, sort)
select 'sponsored_deal', d.id, 'CRBN', 1
  from public.deals d join public.product_variants v on v.id = d.variant_id join public.products p on p.id = v.product_id
 where d.status = 'active' and p.slug = 'crbn-3x-power-series' and v.label = '14mm';

-- Dev marketplace (local only): fictional sellers around Sarasota, FL with pre-owned listings.
-- Locations are snapped exactly as set_listing_location does (D2). No photos: the app shows
-- placeholder art for listings without images.
do $market$
declare
  sellers text[] := array['Marcus T.', 'Priya K.', 'Jordan R.'];
  ids uuid[] := array[gen_random_uuid(), gen_random_uuid(), gen_random_uuid()];
  i int;
  r record;
  lid uuid;
begin
  for i in 1..3 loop
    insert into auth.users (instance_id, id, aud, role, email, email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
                            created_at, updated_at, confirmation_token, recovery_token, email_change, email_change_token_new)
    values ('00000000-0000-0000-0000-000000000000', ids[i], 'authenticated', 'authenticated', format('seller%s@pickledeals.test', i),
            now(), '{"provider":"email","providers":["email"]}', '{}', now() - interval '200 days', now(), '', '', '', '');
    -- Identities let the dev sellers sign in with an email code too (two-account chat testing).
    insert into auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
    values (ids[i]::text, ids[i], jsonb_build_object('sub', ids[i]::text, 'email', format('seller%s@pickledeals.test', i), 'email_verified', true),
            'email', now(), now(), now());
    update public.profiles set display_name = sellers[i], display_name_source = 'provided', member_since = now() - interval '200 days' where id = ids[i];
  end loop;

  for r in select * from (values
      (1, 'joola-perseus-pro-iv', '16mm', null, 'excellent', 15000, true, false, 27.399, -82.401, 'Lakewood Ranch, FL', 2, 'About 15 sessions on it — moved to the 14mm. Edge guard is clean, face still has good grit. Original cover included.'),
      (2, 'selkirk-vanguard-power-air-invikta', '16mm', null, 'excellent', 12500, true, false, 27.402, -82.395, 'Lakewood Ranch, FL', 4, 'Light use, one small scuff on the edge guard. Pickup weekday evenings.'),
      (3, 'asics-gel-renma', 'Standard', null, 'like_new', 7000, true, false, 27.336, -82.531, 'Sarasota, FL', 1, 'Size 10.5, worn twice. Too narrow for me.'),
      (1, 'lobster-pickle-elite', 'Standard', null, 'good', 52000, true, false, 27.498, -82.575, 'Bradenton, FL', 9, 'Works perfectly; battery holds about 3 hours. Remote included.'),
      (2, 'crbn-3x-power-series', '16mm', null, 'like_new', 13000, true, true, 27.341, -82.540, 'Sarasota, FL', 3, 'Played twice, switching to 14mm. Happy to ship.'),
      (3, 'selkirk-core-line-backpack', 'Standard', null, 'excellent', 4500, true, true, 27.100, -82.454, 'Venice, FL', 6, 'Clean, all zippers work.'),
      (1, 'joola-perseus-pro-iv', '16mm', null, 'like_new', 14500, false, true, 27.950, -82.457, 'Tampa, FL', 5, 'Ships only — like new, under 5 sessions.'),
      (2, null, null, 'Wooden practice paddle (1990s)', 'fair', 2000, true, false, 27.336, -82.530, 'Sarasota, FL', 7, 'Old-school wooden paddle, fun for drills. Heavy.')
    ) as t(seller, product_slug, variant_label, custom_title, cond, price, pickup, ships, lat, lng, area, days_ago, body)
  loop
    insert into public.listings (seller_id, product_id, variant_id, category_id, custom_title, condition, price_cents,
                                 description, pickup, ships, status, published_at, created_at)
    select ids[r.seller], p.id, v.id, coalesce(p.category_id, (select id from public.categories where slug = 'paddles')),
           r.custom_title, r.cond::public.listing_condition, r.price, r.body, r.pickup, r.ships,
           case when r.product_slug = 'lobster-pickle-elite' then 'pending' else 'active' end::public.listing_status,
           now() - make_interval(days => r.days_ago), now() - make_interval(days => r.days_ago)
      from (select 1) one
      left join public.products p on p.slug = r.product_slug
      left join public.product_variants v on v.product_id = p.id and v.label = r.variant_label
    returning id into lid;
    insert into public.listing_private (listing_id) values (lid);
    insert into public.listing_locations (listing_id, public_point, geohash6, area_label)
    select lid, s.point, s.geohash, r.area from public.snap_point(r.lat, r.lng, 6) s;
    -- D3: custom items wait in the admin catalog queue, exactly as publish_listing queues them.
    if r.product_slug is null then
      insert into public.listing_catalog_reviews (listing_id, suggestions)
      values (lid, public.suggest_catalog_matches(r.custom_title, null));
    end if;
  end loop;
  -- One sold listing so "what it sells for" has history.
  update public.listings set status = 'sold', sold_price_cents = 13500, sold_at = now() - interval '3 days'
   where id = (select l.id from public.listings l join public.products p on p.id = l.product_id
                where p.slug = 'joola-perseus-pro-iv' and l.price_cents = 14500);

  -- A demo thread (Phase 8): Priya asks Marcus about his Perseus. Inserted as the participants,
  -- through the same triggers the app uses (previews, read state, Realtime, push rows).
  lid := (select l.id from public.listings l join public.products p on p.id = l.product_id
           where p.slug = 'joola-perseus-pro-iv' and l.price_cents = 15000);
  insert into public.conversations (id, listing_id, buyer_id, seller_id) values (gen_random_uuid(), lid, ids[2], ids[1])
  returning id into lid;
  insert into public.conversation_participants (conversation_id, user_id, role) values (lid, ids[2], 'buyer'), (lid, ids[1], 'seller');
  insert into public.messages (conversation_id, sender_id, body) values
    (lid, ids[2], 'Hi! Is this still available?'),
    (lid, ids[1], 'Yes! About 15 sessions on it, edge guard is clean.'),
    (lid, ids[2], 'Great. Could I see it this weekend?');
end;
$market$;

-- Local push dispatch: pg_cron → pg_net → the local API gateway (inside the Docker network).
-- Staging/production set these with their own URL and a service key (see supabase/seed/README.md).
select vault.create_secret('http://supabase_kong_pickledeals:8000', 'project_url');
select vault.create_secret(
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU',
  'dispatch_key');

-- DEV ADMIN (local only): admin@pickledeals.test signs in with an email code from Mailpit
-- (http://127.0.0.1:54324). Never created outside a local db reset.
do $admin$
declare
  uid uuid := gen_random_uuid();
begin
  insert into auth.users (instance_id, id, aud, role, email, email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
                          created_at, updated_at, confirmation_token, recovery_token, email_change, email_change_token_new)
  values ('00000000-0000-0000-0000-000000000000', uid, 'authenticated', 'authenticated', 'admin@pickledeals.test', now(),
          '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '');
  insert into auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
  values (uid::text, uid, jsonb_build_object('sub', uid::text, 'email', 'admin@pickledeals.test', 'email_verified', true), 'email', now(), now(), now());
  insert into public.user_roles (user_id, role) values (uid, 'admin');
  update public.profiles set display_name = 'Dev Admin' where id = uid;
end;
$admin$;
`;

const target = join(here, '..', 'seed.sql');
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== sql) {
    console.error('supabase/seed.sql is stale. Run `npm run catalog:seed`.');
    process.exit(1);
  }
  console.log('seed.sql is up to date');
} else {
  writeFileSync(target, sql);
  console.log(`wrote seed.sql: ${payload.products.length} products, ${payload.brands.length} brands, ${payload.categories.length} categories`);
}
