/**
 * Builds supabase/seed.sql from the catalog CSVs (the source of truth) using the same validator as
 * the admin importer. Run with `npm run catalog:seed`; `--check` fails if seed.sql is stale (CI).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildCatalogPayload, buildOfferRecords, csvRecords, dollarsToCents } from '@pickledeals/shared';

const here = dirname(fileURLToPath(import.meta.url));
const read = (name: string) => readFileSync(join(here, 'catalog', name), 'utf8');
const readDev = (name: string) => readFileSync(join(here, 'dev', name), 'utf8');

const { payload, issues } = buildCatalogPayload({
  brands: read('brands.csv'),
  categories: read('categories.csv'),
  products: read('products.csv'),
});

if (issues.length) {
  for (const i of issues) console.error(`${i.file}.csv:${i.line} ${i.message}`);
  process.exit(1);
}

const json = JSON.stringify(payload);
if (json.includes('$catalog$')) throw new Error('payload contains the SQL dollar-quote tag');

// --- Dev retail data (local only; fictional prices) ---------------------------------------------
const retailers = csvRecords(readDev('retailers.csv')).map(({ values }) => values);
const offers = buildOfferRecords(readDev('offers.csv'));
if (offers.issues.length) {
  for (const i of offers.issues) console.error(`dev/offers.csv:${i.line} ${i.message}`);
  process.exit(1);
}
const promos = csvRecords(readDev('promos.csv')).map(({ values: r }) => ({
  retailer_slug: r.retailer_slug,
  code: r.code,
  title: r.title,
  discount_type: r.discount_type,
  discount_value: Number(r.discount_value),
  min_purchase_cents: r.min_purchase_usd ? dollarsToCents(r.min_purchase_usd) : 0,
  target_kind: r.target_kind || null,
  target_slug: r.target_slug || null,
  ends_in_days: Number(r.ends_in_days),
  verified_days_ago: Number(r.verified_days_ago),
  is_exclusive: r.is_exclusive === 'yes',
}));
const retailJson = { retailers: JSON.stringify(retailers), offers: JSON.stringify(offers.records), promos: JSON.stringify(promos) };
for (const v of Object.values(retailJson)) if (v.includes('$dev$')) throw new Error('dev data contains the SQL dollar-quote tag');

const sql = `-- GENERATED by supabase/seed/build-seed.ts from supabase/seed/catalog/*.csv — do not edit.
-- Development catalog: real brands and models; MSRPs are approximate (see supabase/seed/README.md).
-- ${payload.brands.length} brands · ${payload.categories.length} categories · ${payload.products.length} products
do $seed$
declare
  report jsonb;
begin
  report := public.import_catalog($catalog$${json}$catalog$::jsonb, false);
  if not (report ->> 'applied')::boolean then
    raise exception 'catalog seed failed: %', report -> 'errors';
  end if;
  raise notice 'catalog seed: %', report - 'errors';
end;
$seed$;

-- DEVELOPMENT RETAIL DATA (supabase/seed/dev/*.csv): fictional prices for local testing only.
-- Fictional shops use reserved .example domains; Amazon offers carry no price (D1).
-- ${retailers.length} retailers · ${offers.records.length} offer rows · ${promos.length} promo codes
insert into public.retailers (slug, name, kind, domain, price_display_default)
select slug, name, kind::public.retailer_kind, domain, price_display_default::public.price_display
  from jsonb_to_recordset($dev$${retailJson.retailers}$dev$::jsonb)
       as x(slug text, name text, kind text, domain text, price_display_default text);

do $offers$
declare
  report jsonb;
begin
  report := public.ingest_offers('csv', $dev$${retailJson.offers}$dev$::jsonb, false);
  if not (report ->> 'applied')::boolean then
    raise exception 'dev offer seed failed: %', report -> 'errors';
  end if;
  raise notice 'dev offers: %', report - 'errors' - 'queued';
end;
$offers$;

-- Synthetic 120-day history for priced offers, so charts and deal quality have data: a gentle
-- random walk with retail-style prices ($x.99), changing every few days.
do $history$
declare
  o     record;
  d     integer;
  price integer;
begin
  perform setseed(0.42);
  for o in select id, price_cents, shipping_cents from public.retailer_offers where price_display = 'show' order by external_ref nulls first, url loop
    price := round(o.price_cents * (0.98 + random() * 0.14));
    for d in reverse 120..1 loop
      if d % 5 = 0 and random() < 0.6 then
        price := greatest(round(price * (0.955 + random() * 0.09) / 100) * 100 - 1, 99);
        insert into public.price_points (offer_id, observed_at, price_cents, shipping_cents, in_stock, price_display)
        values (o.id, now() - make_interval(days => d), price, o.shipping_cents, true, 'show');
      end if;
    end loop;
  end loop;
end;
$history$;

insert into public.promo_codes (retailer_id, code, title, discount_type, discount_value, min_purchase_cents, ends_at, verified_at, is_exclusive)
select r.id, p.code, p.title, p.discount_type::public.discount_type, p.discount_value, p.min_purchase_cents,
       now() + make_interval(days => p.ends_in_days), now() - make_interval(days => p.verified_days_ago), p.is_exclusive
  from jsonb_to_recordset($dev$${retailJson.promos}$dev$::jsonb)
       as p(retailer_slug text, code text, title text, discount_type text, discount_value int, min_purchase_cents int,
            target_kind text, target_slug text, ends_in_days int, verified_days_ago int, is_exclusive boolean)
  join public.retailers r on r.slug = p.retailer_slug;

insert into public.promo_code_targets (promo_id, product_id, category_id)
select pc.id,
       case when p.target_kind = 'product' then (select id from public.products where slug = p.target_slug) end,
       case when p.target_kind = 'category' then (select id from public.categories where slug = p.target_slug) end
  from jsonb_to_recordset($dev$${retailJson.promos}$dev$::jsonb) as p(retailer_slug text, code text, target_kind text, target_slug text)
  join public.retailers r on r.slug = p.retailer_slug
  join public.promo_codes pc on pc.retailer_id = r.id and pc.code = p.code
 where p.target_kind is not null;

select public.refresh_variant_price_stats(variant_id) from (select distinct variant_id from public.retailer_offers) v;

-- Dev curation: a staff pick, an editorial collection and a labelled sponsored placement.
update public.deals d set is_staff_pick = true
  from public.product_variants v join public.products p on p.id = v.product_id
 where d.variant_id = v.id and d.status = 'active' and p.slug = 'selkirk-vanguard-power-air-invikta';

insert into public.collections (slug, title, subtitle, eyebrow, sort)
values ('court-shoes-on-sale', 'Court shoes on sale', 'Pickleball-specific shoes at their best prices', 'STAFF PICKS · UPDATED DAILY', 1);
insert into public.collection_items (collection_id, product_id, sort)
select c.id, p.id, row_number() over (order by p.name)
  from public.collections c, public.products p join public.categories cat on cat.id = p.category_id
 where c.slug = 'court-shoes-on-sale' and cat.slug = 'shoes';

insert into public.placements (kind, deal_id, campaign, sort)
select 'sponsored_deal', d.id, 'CRBN', 1
  from public.deals d join public.product_variants v on v.id = d.variant_id join public.products p on p.id = v.product_id
 where d.status = 'active' and p.slug = 'crbn-3x-power-series' and v.label = '14mm';

-- DEV ADMIN (local only): admin@pickledeals.test signs in with an email code from Mailpit
-- (http://127.0.0.1:54324). Never created outside a local db reset.
do $admin$
declare
  uid uuid := gen_random_uuid();
begin
  insert into auth.users (instance_id, id, aud, role, email, email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
                          created_at, updated_at, confirmation_token, recovery_token, email_change, email_change_token_new)
  values ('00000000-0000-0000-0000-000000000000', uid, 'authenticated', 'authenticated', 'admin@pickledeals.test', now(),
          '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '');
  insert into auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
  values (uid::text, uid, jsonb_build_object('sub', uid::text, 'email', 'admin@pickledeals.test', 'email_verified', true), 'email', now(), now(), now());
  insert into public.user_roles (user_id, role) values (uid, 'admin');
  update public.profiles set display_name = 'Dev Admin' where id = uid;
end;
$admin$;
`;

const target = join(here, '..', 'seed.sql');
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== sql) {
    console.error('supabase/seed.sql is stale. Run `npm run catalog:seed`.');
    process.exit(1);
  }
  console.log('seed.sql is up to date');
} else {
  writeFileSync(target, sql);
  console.log(`wrote seed.sql: ${payload.products.length} products, ${payload.brands.length} brands, ${payload.categories.length} categories`);
}
