/**
 * Builds supabase/seed.sql from the catalog CSVs (the source of truth) using the same validator as
 * the admin importer. Run with `npm run catalog:seed`; `--check` fails if seed.sql is stale (CI).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildCatalogPayload } from '@pickledeals/shared';

const here = dirname(fileURLToPath(import.meta.url));
const read = (name: string) => readFileSync(join(here, 'catalog', name), 'utf8');

const { payload, issues } = buildCatalogPayload({
  brands: read('brands.csv'),
  categories: read('categories.csv'),
  products: read('products.csv'),
});

if (issues.length) {
  for (const i of issues) console.error(`${i.file}.csv:${i.line} ${i.message}`);
  process.exit(1);
}

const json = JSON.stringify(payload);
if (json.includes('$catalog$')) throw new Error('payload contains the SQL dollar-quote tag');

const sql = `-- GENERATED by supabase/seed/build-seed.ts from supabase/seed/catalog/*.csv — do not edit.
-- Development catalog: real brands and models; MSRPs are approximate (see supabase/seed/README.md).
-- ${payload.brands.length} brands · ${payload.categories.length} categories · ${payload.products.length} products
do $seed$
declare
  report jsonb;
begin
  report := public.import_catalog($catalog$${json}$catalog$::jsonb, false);
  if not (report ->> 'applied')::boolean then
    raise exception 'catalog seed failed: %', report -> 'errors';
  end if;
  raise notice 'catalog seed: %', report - 'errors';
end;
$seed$;
`;

const target = join(here, '..', 'seed.sql');
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== sql) {
    console.error('supabase/seed.sql is stale. Run `npm run catalog:seed`.');
    process.exit(1);
  }
  console.log('seed.sql is up to date');
} else {
  writeFileSync(target, sql);
  console.log(`wrote seed.sql: ${payload.products.length} products, ${payload.brands.length} brands, ${payload.categories.length} categories`);
}
